name 'bmcwls'
maintainer 'James Calise'
maintainer_email 'james.calise@oracle.com'
license 'GPL v3'
description 'Installs/Configures WLS 12.2.1.1'
long_description 'Installs/Configures WLS 12.2.1.1'
version '0.1.3'
chef_version '~> 12'
supports 'centos', '>= 7'
issues_url 'https://github.com/jimmycal/bmc_wls/issues'
source_url 'https://github.com/jimmycal/bmc_wls'
depends 'java','~> 1.50.0'
depends 'firewall', '~> 2.6.2'
depends 'systemd', '2.0.0'
depends 'chef-sugar', '~> 3.4.0'
